### ISSUE TITLE
No module named 'oldfile'

### ISSUE THREAD

**Issue by leayeap** [cjj535/FedVAE#1]
Traceback (most recent call last):
  File "D:\download\FedVAE-main\main.py", line 9, in <module>
    from server import *
  File "D:\download\FedVAE-main\server.py", line 11, in <module>
    from oldfile.kmeans import *
ModuleNotFoundError: No module named 'oldfile'

**Comment by cjj535** [comment]
Sorry, I forget to delete the "import"
